language: csharp
sudo: required
services:
  - docker

os:
   - osx
   - linux

script:
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then ./build-darwin.sh; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then ./build.sh; fi
