install:
  - appveyor DownloadFile https://slproweb.com/download/Win64OpenSSL-1_0_2f.exe
  - ps: Start-Process Win64OpenSSL-1_0_2f.exe -ArgumentList "/silent /verysilent /sp- /suppressmsgboxes"
  - cmd: git submodule update --init --recursive

build_script:
  - cmd: build.cmd
