environment:
  NASM_URL: http://www.nasm.us/pub/nasm/releasebuilds/2.12.02/win64/nasm-2.12.02-win64.zip

install:
  # install NASM
  - appveyor DownloadFile "%NASM_URL%" -FileName "c:\nasm.zip"
  - 7z x "c:\nasm.zip" -oc:\
  - move nasm-* NASM
  - set PATH=%PATH%;c:\NASM;
  - nasm -v

build_script:
  - cmd: build.cmd
